/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef page_H
#define page_H

#include <thrift/TDispatchProcessor.h>
#include "page_types.h"

namespace page {

class pageIf {
 public:
  virtual ~pageIf() {}
  virtual void getPageBody(std::string& _return, const std::string& pageurl) = 0;
};

class pageIfFactory {
 public:
  typedef pageIf Handler;

  virtual ~pageIfFactory() {}

  virtual pageIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(pageIf* /* handler */) = 0;
};

class pageIfSingletonFactory : virtual public pageIfFactory {
 public:
  pageIfSingletonFactory(const boost::shared_ptr<pageIf>& iface) : iface_(iface) {}
  virtual ~pageIfSingletonFactory() {}

  virtual pageIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(pageIf* /* handler */) {}

 protected:
  boost::shared_ptr<pageIf> iface_;
};

class pageNull : virtual public pageIf {
 public:
  virtual ~pageNull() {}
  void getPageBody(std::string& /* _return */, const std::string& /* pageurl */) {
    return;
  }
};

typedef struct _page_getPageBody_args__isset {
  _page_getPageBody_args__isset() : pageurl(false) {}
  bool pageurl;
} _page_getPageBody_args__isset;

class page_getPageBody_args {
 public:

  page_getPageBody_args() : pageurl() {
  }

  virtual ~page_getPageBody_args() throw() {}

  std::string pageurl;

  _page_getPageBody_args__isset __isset;

  void __set_pageurl(const std::string& val) {
    pageurl = val;
  }

  bool operator == (const page_getPageBody_args & rhs) const
  {
    if (!(pageurl == rhs.pageurl))
      return false;
    return true;
  }
  bool operator != (const page_getPageBody_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const page_getPageBody_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class page_getPageBody_pargs {
 public:


  virtual ~page_getPageBody_pargs() throw() {}

  const std::string* pageurl;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _page_getPageBody_result__isset {
  _page_getPageBody_result__isset() : success(false) {}
  bool success;
} _page_getPageBody_result__isset;

class page_getPageBody_result {
 public:

  page_getPageBody_result() : success() {
  }

  virtual ~page_getPageBody_result() throw() {}

  std::string success;

  _page_getPageBody_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const page_getPageBody_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const page_getPageBody_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const page_getPageBody_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _page_getPageBody_presult__isset {
  _page_getPageBody_presult__isset() : success(false) {}
  bool success;
} _page_getPageBody_presult__isset;

class page_getPageBody_presult {
 public:


  virtual ~page_getPageBody_presult() throw() {}

  std::string* success;

  _page_getPageBody_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class pageClient : virtual public pageIf {
 public:
  pageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  pageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getPageBody(std::string& _return, const std::string& pageurl);
  void send_getPageBody(const std::string& pageurl);
  void recv_getPageBody(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class pageProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<pageIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (pageProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getPageBody(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  pageProcessor(boost::shared_ptr<pageIf> iface) :
    iface_(iface) {
    processMap_["getPageBody"] = &pageProcessor::process_getPageBody;
  }

  virtual ~pageProcessor() {}
};

class pageProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  pageProcessorFactory(const ::boost::shared_ptr< pageIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< pageIfFactory > handlerFactory_;
};

class pageMultiface : virtual public pageIf {
 public:
  pageMultiface(std::vector<boost::shared_ptr<pageIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~pageMultiface() {}
 protected:
  std::vector<boost::shared_ptr<pageIf> > ifaces_;
  pageMultiface() {}
  void add(boost::shared_ptr<pageIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getPageBody(std::string& _return, const std::string& pageurl) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getPageBody(_return, pageurl);
    }
    ifaces_[i]->getPageBody(_return, pageurl);
    return;
  }

};

} // namespace

#endif
